### PR TITLE
add credentialvault

### PR DESCRIPTION
**Pull request by daboxu**

### CODE REVIEW

**Comment by DamirLisak** [comment]
I have tested it - it works. You can merge.

**Comment by daboxu** [comment]
@DamirLisak updated the reference, appear it should be  <Link>CredentialVault.cs</Link>, would you mind trying again?

**Comment by DamirLisak** [comment]
@daboxu i tried it again and it works. You can merge. Don't forget to make nuget-package - thanks!

**Comment by DamirLisak** [comment]
@daboxu : Can you merge to master and publish it on nuget please?

**Comment by daboxu** [comment]
@DamirLisak sorry for the delay, it's out 
 as version 1.0.10 https://www.nuget.org/packages/Microsoft.OneDriveSDK.Authentication/1.0.10

**Pull request merged**
